name: 'Satellite file upload (alpha)'
description: 'Upload a new Kubernetes resource to IBM Cloud Satellite (alpha)'
inputs:
  apikey:
    description: 'IBM Cloud API key'
    required: true
  channel_id:
    description: 'Satellite Config channel_id'
    required: true
  filename:
    description: 'File to upload'
    required: true
  version_name:
    description: 'Name of the new version'
    required: true
outputs:
  versionid:
    description: 'The ID of the new version uploaded'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: arrow-up-circle
  color: blue
